name: SSH into EC2 and Execute Command

on:
  push:
    branches:
      - main

jobs:
  ssh_into_ec2:
    name: SSH into EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Set up SSH Key
        uses: webfactory/ssh-agent@v0.5.0
        with:
#            host: 18.133.175.42
#            username: ubuntu
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
      - name: Build Docker image
        run: docker build -t my-image:latest .
        
      - name: Save Docker image as tar file
        run: docker save -o my-image.tar my-image:latest

      - name: SSH into EC2 and Build Docker Image
        run: |
          scp -o StrictHostKeyChecking=no -i $HOME/.ssh/github-actions my-image.tar ubuntu@18.133.228.162:/home/ubuntu
      
      - name: Load Docker Image on EC2
        run: |
            ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/github-actions ubuntu@18.133.228.162 'docker load -i /home/ubuntu/my-image.tar'

      
