name: SSH into EC2 and Execute Command

on:
  push:
    branches:
      - main

jobs:
  ssh_into_ec2:
    name: SSH into EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH Key
        uses: webfactory/ssh-agent@v0.5.0
        with:
            host: 18.133.175.42
            username: ubuntu
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into EC2 and Execute Command
        run: |
          ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/github-actions ubuntu@18.133.175.42 'echo "hello, world" >> test.txt
''